apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-server
spec:
  selector:
    matchLabels:
      app: store-server
  replicas: 1
  template:
    metadata:
      labels:
        app: store-server
    spec:
      containers:
      - name: store-server
        image: chiranthans23/dcscproj-store-server:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: "request-queue"
        - name: REDIS_PORT
          value: "6379"
        - name: DB1_HOST
          value: "store-mysql1"
        - name: DB2_HOST
          value: "store-mysql2"
        - name: DB3_HOST
          value: "store-mysql3"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: storedb-secrets
             key: db_root_password
          