apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
spec:
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit
          image: mongo
          ports:
            - containerPort: 27017