apiVersion: batch/v1
kind: CronJob
metadata:
  name: request-scheduled
spec:
  schedule: '*/2 * * * *'
  jobTemplate:
    metadata:
      name: request-scheduled
    spec:
      template:
        spec:
          containers:
          - image: chiranthans23/dcscproj-request-scheduled:v7
            env:
              - name: REDIS_HOST
                value: "request-queue"
              - name: REDIS_PORT
                value: "6379"
              - name: F_STORE_HOST
                value: store-server
              - name: AUDIT_HOST
                value: audit
            imagePullPolicy: Never
            name: request-scheduled
            resources: {}
          restartPolicy: Never
