apiVersion: v1
kind: Service
metadata:
  name: station-mysql
  labels:
    app: station-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: station-mysql
  selector:
    app: station-db
  type: LoadBalancer