apiVersion: v1
kind: Service
metadata:
  name: request-queue
  labels:
    app: request-queue
spec:
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
  selector:
    app: request-queue