apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-queue
spec:
  selector:
    matchLabels:
      app: request-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: request-queue
    spec:
      containers:
      - name: request-queue-container
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
---
